from django.test import TestCase
from ..models import Photo


class PhotoTestCase(TestCase):
    def setUp(self):
        Photo.objects.get_or_create(title="Model Test object 1",
                                    albumId=2000,
                                    url="https://via.placeholder.com/600/92c952",
                                    width=600,
                                    height=600,
                                    dominant_color="92c952")

    def test_dominant_color(self):
        """Test dominant color generated by model's methods."""
        photo = Photo.objects.get(title="Model Test object 1")

        self.assertEqual(photo.dominant_color, '92c952')

    def test_title_max_length(self):
        photo = Photo.objects.get(title="Model Test object 1")
        max_length = photo._meta.get_field('title').max_length

        self.assertEqual(max_length, 200)

    def dominant_color_max_length(self):
        photo = Photo.objects.get(title="Model Test object 1")
        max_length = photo._meta.get_field('dominant_color').max_length

        self.assertEqual(max_length, 6)

    def test_url_max_length(self):
        photo = Photo.objects.get(title="Model Test object 1")
        max_length = photo._meta.get_field('url').max_length

        self.assertEqual(max_length, 200)
